services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - auth-service
      # - geo-service
      # - inventory-service
      # - orders-service
      # - reports-service

  auth-service:
    build: ./auth-service
    ports:
      - "4001:4001"
    env_file:
      - ./.env
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  # geo-service:
  #   build: ./geo-service
  #   ports:
  #     - "4002:4002"

  # inventory-service:
  #   build: ./inventory-service
  #   ports:
  #     - "4003:4003"

  # orders-service:
  #   build: ./orders-service
  #   ports:
  #     - "4004:4004"
  
  # reports-service:
  #   build: ./reports-service
  #   ports:
  #     - "4005:4005"
volumes:
  pgdata:

