name: CI - Backend Microservices

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file
        run: |
          echo "GATEWAY_PORT=${{ vars.GATEWAY_PORT }}" >> .env
          echo "GATEWAY_URL=${{ vars.GATEWAY_URL }}" >> .env
          echo "AUTH_URL=${{ vars.AUTH_URL }}" >> .env
          echo "GEO_URL=${{ vars.GEO_URL }}" >> .env
          echo "INVENTORY_URL=${{ vars.INVENTORY_URL }}" >> .env
          echo "ORDERS_URL=${{ vars.ORDERS_URL }}" >> .env
          echo "REPORTS_URL=${{ vars.REPORTS_URL }}" >> .env
          echo "AUTH_DATABASE_URL=${{ vars.AUTH_DATABASE_URL }}" >> .env
          echo "AUTH_DIRECT_URL=${{ vars.AUTH_DIRECT_URL }}" >> .env
          echo "INVENTORY_DATABASE_URL=${{ vars.INVENTORY_DATABASE_URL }}" >> .env
          echo "INVENTORY_DIRECT_URL=${{ vars.INVENTORY_DIRECT_URL }}" >> .env
          echo "ORDERS_DATABASE_URL=${{ vars.ORDERS_DATABASE_URL }}" >> .env
          echo "ORDERS_DIRECT_URL=${{ vars.ORDERS_DIRECT_URL }}" >> .env
          echo "AUTH_PORT=${{ vars.AUTH_PORT }}" >> .env
          echo "JWT_SECRET=${{ vars.JWT_SECRET }}" >> .env
          echo "API_HOST=${{ vars.API_HOST }}" >> .env
          echo "NODE_ENV=${{ vars.NODE_ENV }}" >> .env

      - name: Build docker-compose services
        run: docker compose -f docker-compose.yml build

      - name: Start containers
        run: docker compose -f docker-compose.yml up -d

      - name: Wait for services to be ready
        run: sleep 30

      - name: Check if containers are healthy
        run: |
          set -e

          echo "Verificando health de auth-service..."
          curl -v http://localhost:3000/auth/auth/health || {
            echo "auth-service está unhealthy"
          }

          echo "Verificando health de inventory-service..."
          curl -v http://localhost:3000/inventory/inventory/health || {
            echo "inventory-service está unhealthy"
          }

      - name: Run auth tests
        run: docker exec logistics-backend-auth-service-1 npm test

      - name: Deploy on Render
        if: github.ref == 'refs/heads/develop'
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
