name: CI - Backend Microservices

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file for auth-service
        run: |
          echo "AUTH_DATABASE_URL=${{ vars.AUTH_DATABASE_URL }}" > auth-service/.env
          echo "AUTH_PORT=4001" >> auth-service/.env


      - name: Build docker-compose services
        run: docker compose -f docker-compose.yml build

      - name: Start containers
        run: docker compose -f docker-compose.yml up -d

      - name: Wait for services to be ready
        run: sleep 10

      - name: Check if containers are healthy
        run: |
          set -e

          echo "Verificando health de auth-service..."
          if ! curl --silent --fail http://localhost:4001/health; then
            echo "auth-service está unhealthy"
            exit 1
          fi
          echo "auth-service está healthy"

      - name: Run auth tests
        run: docker exec auth-service npm test || echo "No tests yet"
