name: CI - Backend Microservices

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker-compose services
        run: docker compose -f docker-compose.yml build

      - name: Start containers
        run: docker compose -f docker-compose.yml up -d

      - name: Wait for services to be ready
        run: sleep 10

      # Optional: agregar test
      - name: Run tests (si tenés test.js o npm test en un servicio)
        run: docker exec auth-service npm test || echo "No tests yet"
